@startuml
left to right direction
actor User
actor App
rectangle "Use Cases" {
    usecase "Scream" as RecordSound
    usecase "Turn light on" as MonitorLight
    usecase "View statistics" as ViewStatistics
    usecase "Start measuring" as Startmeasuring
    usecase "Insert morning Data" as insert
}

User --> RecordSound: Initiates
User --> MonitorLight: Initiates
User --> ViewStatistics: Initiates

App --> insert
App --> Startmeasuring

RecordSound --> insert
MonitorLight --> insert

RecordSound --> Startmeasuring
MonitorLight --> Startmeasuring



@enduml
